apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out converted
    kompose.service.type: LoadBalancer
    kompose.version: 1.19.0 (f63a961c)
    metallb.universe.tf/allow-shared-ip: plex
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex-tcp
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.202
  ports:
  - name: '22'
    port: 22
    targetPort: 22
  - name: '32400'
    port: 32400
    targetPort: 32400
  - name: '3005'
    port: 3005
    targetPort: 3005
  - name: '8324'
    port: 8324
    targetPort: 8324
  - name: '32469'
    port: 32469
    targetPort: 32469
  selector:
    io.kompose.service: plex
  type: LoadBalancer
status:
  loadBalancer: {}
