apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-mongo-config-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: unifi-mongo-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /volume1/unifi/mongo-config
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
