apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: pihole-dnsmasq
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /volume1/pihole/dnsmasq
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
