apiVersion: v1
kind: PersistentVolume
metadata:
  name: tester-temp-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: tester
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /volume1/plex/Temp
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  claimRef:
    name: tester-temp-pvc
    namespace: default
  volumeMode: Filesystem
