version: "3"
services:
  docker-registry:
    image: registry:2.6.2
    ports:
      - "443:5000/tcp"
    labels:
      kompose.service.type: LoadBalancer
    volumes:
      - 'docker-registry:/var/lib/registry/'
    restart: always
