version: "3"
services:
  docker-registry:
    image: registry:2.7.1
    ports:
      - "443:443/tcp"
    labels:
      kompose.service.type: LoadBalancer
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/docker.lan.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/docker.lan.key"
    volumes:
      - 'docker-registry:/var/lib/registry/'
    restart: always

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "80:80/tcp"
    labels:
      kompose.service.type: LoadBalancer
    environment:
      ENV_DOCKER_REGISTRY_HOST: "docker-registry.default.svc.cluster.local"
      ENV_DOCKER_REGISTRY_PORT: "443"
      ENV_DOCKER_REGISTRY_USE_SSL: "1"
      ENV_REGISTRY_PROXY_FQDN: "docker.lan"
    restart: always

