apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: jupyter
  name: jupyter-home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      reserved.for: jupyter-home
