apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: jupyter
  labels:
    name: jupyter
  name: jupyter
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.205
  ports:
  - name: '80'
    port: 80 
    targetPort: 8888
  selector:
    name: jupyter 
  type: LoadBalancer
