# DEVICES
device_to_code:
    light: aaa
    fan: bbb
    fogger: ccc

code_to_device:
    aaa: light
    bbb: fan
    ccc: fogger

default-state:
    light: on
    fan: off
    fogger: off

# TASKS
fan_n_fog:
    fan_time: 45 # Seconds
    wait_time: 15 # Seconds
    fog_time: 90 # Seconds

light_toggle:
    wait_time: 10 # Seconds
    fail_wait_time: 5 # Minutes

daily_darkness:
    duration: 360 # Minutes
    begin_hour: 19 # 24-hour time
    begin_minute: 5 # Minutes past hour

# SCHEDULER
apscheduler-config:
  apscheduler.jobstores.default:
    class: "apscheduler.jobstores.redis:RedisJobStore"
    host: "terrarium-redis"
  apscheduler.executors.default:
    class: "apscheduler.executors.pool:ThreadPoolExecutor"
    max_workers: 1
  apscheduler.timezone: "US/Central"
