apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-home-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: jupyter-home
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /volume1/jupyter/home
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
