apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    service: pihole
  name: pihole-tcp
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.192
  ports:
  - name: '80'
    port: 80
    targetPort: 80
  - name: '443'
    port: 443
    targetPort: 443
  selector:
    service: pihole
  type: LoadBalancer
