apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: pihole
    spec:
      containers:
      - env:
        - name: DNS1
          value: 127.0.0.1
        - name: DNS2
          value: 192.168.1.1
        - name: IPv6
          value: 'False'
        - name: ServerIP
          value: 192.168.2.192
        - name: TZ
          value: America/Chicago
        - name: DNSMASQ_USER
          value: root
        - name: WEBPASSWORD
        image: pihole/pihole:2023.03.1
        name: pihole
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/pihole/
          name: pihole-config
        - mountPath: /etc/dnsmasq.d/
          name: pihole-dnsmasq
          subPath: data 

      restartPolicy: Always

      enableServiceLinks: false

      volumes:
      - name: pihole-config
        persistentVolumeClaim:
          claimName: pihole-config
      - name: pihole-dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq
