apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    service: pihole
  name: pihole-udp
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.192
  ports:
  - name: '53'
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    service: pihole
  type: LoadBalancer
