apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: pihole
  name: pihole-dnsmasq
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      reserved.for: pihole-dnsmasq
