apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: pihole
  name: pihole-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      reserved.for: pihole-config
