apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-video-vids-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: unifi-video-vids
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  nfs:
    path: /volume1/unifi-video/vids
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
