apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    reserved.for: plex-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /volume1/plex/Config
    server: nas.lan
  mountOptions:
  - local_lock=posix
  - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
